AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Sam Template

Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
    
  HelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: HelloFunction
      CodeUri: ./hello
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /hello
            Method: GET
  
Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref MyApi

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/'
